name: Web Automation Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v2.1.0

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Debug Environment Variables
        run: |
          echo "GITHUB_SERVER_URL=${GITHUB_SERVER_URL}"
          echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"
          echo "GITHUB_RUN_ID=${GITHUB_RUN_ID}"

      - name: Run API Tests
        run: ./gradlew cucumberApi
        env:
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}

      - name: Run UI Tests
        run: ./gradlew cucumber
        env:
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}

      - name: Upload Cucumber HTML report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report-html
          path: reports/cucumber.html

      - name: Upload Cucumber JSON report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report-json
          path: reports/cucumber.json
