name: Web Automation Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v2.1.0

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run UI Automation Tests
        run: ./gradlew cucumber
        shell: bash

      - name: Upload Cucumber HTML report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report-html
          path: reports/cucumber.html

      - name: Upload Cucumber JSON report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report-json
          path: reports/cucumber.json

  dependency-submission:
    runs-on: ubuntu-latest
    name: Dependency Submission
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Submit dependencies to GitHub
        uses: gradle/actions/dependency-submission@v3
